# General
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$colorPicker = hyprpicker --autocopy --format=hex
$lock = hyprlock

# Screenshots
$shot-region = mkdir -p ~/Pictures/screenshots && grimblast copysave area ~/Pictures/screenshots/$(date +%F_%H-%M-%S-%3N).png
$shot-window = mkdir -p ~/Pictures/screenshots && grimblast copysave active ~/Pictures/screenshots/$(date +%F_%H-%M-%S-%3N).png
$shot-screen = mkdir -p ~/Pictures/screenshots && grimblast copysave output ~/Pictures/screenshots/$(date +%F_%H-%M-%S-%3N).png
