# General
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$colorPicker = hyprpicker --autocopy --format=hex
$lock = hyprlock

# Screenshots
$shot-region = grimblast save area | tee ~/Pictures/screenshots/$(date +%F_%H-%M-%S).png | wl-copy
$shot-window = grimblast save active | tee ~/Pictures/screenshots/$(date +%F_%H-%M-%S).png | wl-copy
$shot-screen = grimblast save output | tee ~/Pictures/screenshots/$(date +%F_%H-%M-%S).png | wl-copy
